swagger: '2.0'
info:
  title: API fechas
  description: >-
    Solución de desafío previred (Fechas faltantes).
  version: 1.0.0
  contact:
    email: ajamask@gmail.com
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache-2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: localhost:8180
basePath: /api-fechas
schemes:
  - http
tags:
  - name: fechas
    description: Solución a fechas faltantes
    externalDocs:
      description: Mas información
      url: 'http://swagger.io'
paths:
  /fechas:
    post:
      tags:
        - fechas
      summary: Periodo y fechas faltantes
      description: ''
      operationId: getFechas
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: periodo
          description: Periodo con lista de fechas
          required: true
          schema:
            $ref: '#/definitions/Periodo'
      responses:
        '200':
          description: Operación Exitosa
          schema:
            $ref: '#/definitions/PeriodoSolucion'
        '400':
          description: Entrada Inválida
definitions:
  Periodo:
    type: object
    properties:
      id:
        type: integer
        format: int64
      fechaCreacion:
        type: string
        format: date
      fechaFin:
        type: string
        format: date
      fechas:
        type: array
        items:
          type: string
          format: date
  PeriodoSolucion:
    type: object
    properties:
      id:
        type: integer
        format: int64
      fechaCreacion:
        type: string
        format: date
      fechaFin:
        type: string
        format: date
      fechas:
        type: array
        items:
          type: string
          format: date
      fechasFaltantes:
        type: array
        items:
          type: string
          format: date
externalDocs:
  description: Especificación de swagger
  url: 'https://swagger.io/docs/specification/about/'
